### ISSUE TITLE
Design discussion: numerous calls to UriMap/Unmap etc

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Website#238]
I barely know how the Website app is working underneath. The initial impression I got is that admin registers needed URIs, which he adds manually via Website app UI. Admin can register mixed URIs then, which is good. 
Reminder:
**Specific URI**: /WebsiteProvider_AcceptanceHelperTwo/content/test55
**Handler URI**: /WebsiteProvider_AcceptanceHelperTwo/content/{?}
**Mixed URI**: /WebsiteProvider_AcceptanceHelperTwo/content/{test55}

Expected scenario that I thought of: admin registers needed URIs (handler or mixed, no specific), they are saved in database and then re-applied on Website application restart. Something like that.

However, now it seems WebsiteProvider does blending almost on every request, and then unblending, meaning numerous calls to `MapUri/UnmapUri` and does then on incoming specific URIs, not knowing the mixed URIs. There is a special API call I added, but it involves URI matching, and thus is very expensive (that's why you say the slowdown in apps startup before): `Blender.TryGetMixedUriFromSpecific`.

First its a performance problem, since we aim to have hundreds of thousands URI calls per second. And Blender is not suited for that, registering a thousand URI maybe takes a second. In any case, it can't be called on every incoming URI (`MapUri`) and then uncalled (`UnmapUri`) again.
Therefore I think there are some design issues we need to reevaluate. 

CC @un-tone @warpech

**Comment by alemoi** [comment]
https://github.com/Starcounter/Website/issues/237

**Comment by warpech** [comment]
Thanks @alemoi for asking this, this is a legitimate question. 

@un-tone could you pls explain what are these lines used for:

- https://github.com/Starcounter/Website/blob/8913ef61fcb2e13edde7ea7b722f81c09babb005/src/WebsiteProvider/Api/ContentHandlers.cs#L81
- https://github.com/Starcounter/Website/blob/8913ef61fcb2e13edde7ea7b722f81c09babb005/src/WebsiteProvider/Api/ContentHandlers.cs#L94

As @alemoi says, the intended usage of Blender APIs is to call them only at configuration stage, not in every request.

**Comment by un-tone** [comment]
It was implemented in #205 in according to this discussion https://github.com/Starcounter/Minutes/blob/master/BlendingTF/2017-09-14-blending_already_blended.md.

**Comment by un-tone** [comment]
Actually I agree with @alemoi, especially with last changes in Blender it became too expensive to use such approach since to fix fast the current issue we'll have to use `Blender.TryGetMixedUriFromSpecific`.
So I should revert changes from #205, but we should find another solution for that "blending already blended" problem. I'll investigate for it tomorrow.

**Comment by warpech** [comment]
Thanks @un-tone very much for nailing this. I agree #205 should be reverted, but actually this PR is a very clean explanation of what problem we need to solve.

To explan it in one sentence, we are doing *on-the-fly* blending based on conditions ran in a response middleware.

@alemoi a simple way to replicate this problem is: create a `Blender.MapUri` rule that only works for odd requests and does not work for even requests. You cannot make the `Handle.GET` handler aware of this. If you can implement it without calls to `Blender.MapUri`/`Blender.UnmapUri` in middleware (or without Blender converter functions), then we are all set.

**Comment by alemoi** [comment]
> @alemoi a simple way to replicate this problem is: create a Blender.MapUri rule that only works for odd requests and does not work for even requests. You cannot make the Handle.GET handler aware of this. If you can implement it without calls to Blender.MapUri/Blender.UnmapUri in middleware (or without Blender converter functions), then we are all set.

Can you please explain more explicitly? 😄

**Comment by warpech** [comment]
> Can you please explain more explicitly? 😄

1. Write a `Handle.GET` that returns JSON `{"Hello": "World"}`
2. Write another `Handle.GET` that returns JSON `{"Foo": "Bar"}`
3. Write a blending rule that attaches 2 whenever 1 is called
4. Make that blending rule be effective not always, but every second time

In the past, point was achieved by conversion functions or by declaring the blending rule in middleware. Right now it seems that both these methods are not supported anymore so we need another method.

**Comment by alemoi** [comment]
Hmm, seems very specific.  Sounds like there should be a special boolean-returning function, that will be called if given before each blending. If it returns True - then blending is called, otherwise not. And it won't be able to do it via markdown ofc.

**Comment by warpech** [comment]
Because we are doing a specific thing. WebsiteProvide wraps ANY response in a middleware and, based on the request HTTP headers, applies `Blender.API`. For example, it can put `/signin/user` to the Topbar only if the URI begins with `/people` and the port is host is `intranet.company.com`.

**Comment by warpech** [comment]
If @alemoi you understand this now, but still think this cannot be implemented in an elegant way, I think we must remove this feature altogeter from WebsiteEditor. Wheven a user tries to set a blending rule to the default blending point, a warning will show that this blending rule is ineffective.

@alemoi, @un-tone WDYT?

**Comment by un-tone** [comment]
> on-the-fly blending based on conditions ran in a response middleware.

@warpech I didn't catch how your solution solves the current problem? We still will have to make many calls of `Blender.MapUri` on each request, right? Could you please explain it?

**Comment by warpech** [comment]
All I wanted to illustrate is that we need a API to conditionally apply blending rules for an unknown URI.

If this sounds not feasible to @alemoi, then we should remove the feature of supporting blending rules for the *default* blending point of a surface.

**Comment by alemoi** [comment]
As I suggested above I can add a conditional function to Blender API, that would work as following:
right before the blended URI is called, I'm calling the given (by user) delegate function, which if returns TRUE - then I call this blended URI, and if not - then I don't.
But we can think of something better and more generic.

**Comment by alemoi** [comment]
However this sounds like another type of converter delegates, though simplified :)

**Comment by Mihaiii** [comment]
Hi everyone!

Regarding the multiple blending/unblending at every request issue, can we please have a Custom build that doesn't have this problem (even if you undo some changes done in some PR) until you all find a final solution?
I have multiple scenarios in which an error is thrown when navigating in `inside.starcounter.com` and I suspect that the majority of them are related with this issue.

Thank you!

**Comment by warpech** [comment]
My proposal is this:

1. we remove the feature of blending additional content to the "default blending point"
2. whenever a user tries to set a blending rule to the default blending point in WebsiteEditor, we will show a warning that this blending rule is ineffective
3. We make an issue in RebelsLounge about the proposal made by @alemoi in https://github.com/Starcounter/Website/issues/238#issuecomment-337261037 for future consideration. If WebsiteEditor users complain about the lack of this feature, we will reimplement it correctly.

@PatrykSzwer, @un-tone WDYT?

I will not ask our users because I don't think they even realize that we have this feature.

**Comment by un-tone** [comment]
I agree, because I don't like this mapping/unmapping on each request. I guess users can just add additional blending point if they want to get a replacement of this feature.

**Comment by PatrykSzwer** [comment]
I also agree, since it has that impact on performance (and readability as it seems). We just need to properly describe that to user, for him to understand what he should/shouldn't be doing, and we should be good.

**Comment by warpech** [comment]
Thanks, seems that we have an agreement! I have created a fresh issue to implement changes from https://github.com/Starcounter/Website/issues/238#issuecomment-337854121 point 1 and 2.
