### ISSUE TITLE
"WebSocket connection closed" after clicking tabs in specific order

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#298]
### Steps to reproduce
1. Go to `http://localhost:8080/WebsiteEditor`
2. Click two times at tab `Surface groups`
3. Click on `All routes` tab.
### Expected result
No errors
### Actual result
![image](https://user-images.githubusercontent.com/25042256/34200554-d1490f72-e571-11e7-90f3-0d26e88f5d59.png)

##### Starcounter version 2.3.1.8061

cc: @un-tone

**Comment by warpech** [comment]
@PatrykSzwer please always try to report the visible reason for the error if possible.

 "WebSocket connection closed" is not the reason but the symptom of an exception that happens on the server while applying a patch.

The real reason is `Starcounter.DbException: ScErrTransactionClosed....` and is logged in the full form on the server. The error log is available in Administrator > Logs.

**Comment by warpech** [comment]
PRs #309 and #300 went out of scope of the final release of Website. They should be fixed in BlendingProvider.

**Comment by PatrykSzwer** [comment]
In that case I'll just close this issue, and move it to Blending repository already.
